version: 2.1
orbs:
  slack: circleci/slack@4.4.4

jobs:
  fail_build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - run: exit 1
      - slack/notify:
          event: fail
          template: basic_fail_1
  success_build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - run: exit 0
      - slack/notify:
          event: pass
          template: basic_success_1
  fail_build_channel:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - run: exit 1
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: "$STITCH_SOURCES_SLACK"
  success_build_channel:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - run: exit 0
      - slack/notify:
          event: pass
          channel: "$STITCH_SOURCES_SLACK"
          template: basic_success_1



workflows:
  version: 2
  commit:
    jobs:
      - success_build:
          context: circleci-user
      - fail_build:
          context: circleci-user
          require:
            - success_build
      - success_build_channel:
          context: circleci-user
          require:
            - success_build
      - fail_build_channel:
          context: circleci-user
          require:
            - success_build
